Resolve #7: Enable basic core modules and add develop modules for con…
lemberg/draft pull request #14
Opened 2019-01-31 15:58 UTC by ozin7

Enable core modules and add develop modules.

2019-02-21 15:54 UTC, T2L requested changes

2019-02-21 15:54 UTC, T2L commented on draft.info.yml
> +  - drupal:editor
Remove as `drupal:ckeditor` depends on it already

2019-02-21 15:54 UTC, T2L commented on draft.info.yml
> +  - drupal:field
Remove as `drupal:ckeditor` depends on it already

2019-02-21 15:54 UTC, T2L commented on draft.info.yml
> +  - drupal:menu_link_content
Remove as `drupal:menu_ui` depends on it already

2019-02-21 15:54 UTC, T2L commented on draft.info.yml
> +  - drupal:user
Remove as `drupal:core` depends on it already

2019-02-21 15:54 UTC, T2L commented on CHANGELOG.md
>  ## Draft 1.x.x
Move to `Draft 2.x.x` as we are going to do new existing stuff!

2019-02-21 15:54 UTC, T2L commented on draft.info.yml
> +  - drupal:views
Add:
- Contextual Links
- Custom block

2019-02-21 15:54 UTC, T2L commented on config/install/config_split.config_split.develop.yml
> +  field_ui: 0
Add:
- Database logging
- Update manager

2019-02-21 15:54 UTC, T2L commented on CHANGELOG.md
> +- Enable basic core modules and add Views UI and Field UI to the config split settings
Please link issue number, and list all modules

2019-02-21 16:18 UTC, ozin7 commented
@T2L I've fixed your comments, please check!

2019-03-01 09:24 UTC, ribel commented
@ozin7 please resolve conflicts.

2019-03-06 15:12 UTC, merged